# Configuration for the ML project run

## Define model: neural_net or logistic_regression
model: neural_net

## Define number of CV splits (2 for neural net / 5 for logistic regression)
cv_splits: 2

## Define model storage
store_model: true
storage_name: neural_net_2026-02-12_01